" Essentially everything in this configuration is stolen from people smarter
" than me. Many thanks to all of them, notably Chris Toomey, tpope, and the
" ever wise Stack Overflow.

let mapleader=" " " Map leader key to space

function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
        execute 'source' config_file
    endif
  endfor
endfunction

filetype off                  " required for Vundle
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive' " Add nice git bindings/interactions
Plugin 'ctrlpvim/ctrlp.vim' " Fuzzy-finder
Plugin 'scrooloose/nerdcommenter' " Adds easy comment toggling
Plugin 'sheerun/vim-polyglot' " Many languages, syntax, etc.
Plugin 'flazz/vim-colorschemes' " Colorscheme pack
Plugin 'tpope/vim-surround' " Handle quotes, parens, tags much more easily
Plugin 'tpope/vim-repeat'   " Make . work with vim-surround and other plugins
Plugin 'ntpeters/vim-better-whitespace' " Whitespace highlighting and trimming
Plugin 'Valloric/YouCompleteMe' " Auto completion
Plugin 'scrooloose/syntastic' " Syntax checker
Plugin 'sjl/vitality.vim'     " FocusGained,FocusLost events piped from iTerm2
Plugin 'kana/vim-textobj-user' " Declarative API for custom text objects
Plugin 'nelstrom/vim-textobj-rubyblock' " Ruby block text objects

call vundle#end()            " required
filetype plugin indent on    " required

runtime macros/matchit.vim

call s:SourceConfigFilesIn('rcfiles')
