" Essentially everything in this configuration is stolen from people smarter
" than me. Many thanks to all of them, notably Chris Toomey, tpope, and the
" ever wise Stack Overflow.

let mapleader=" " " Map leader key to space

function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
        execute 'source' config_file
    endif
  endfor
endfunction

filetype off                  " required for Vundle
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'SirVer/ultisnips' " Snippet engine
Plugin 'Valloric/YouCompleteMe' " Auto completion
Plugin 'VundleVim/Vundle.vim' " let Vundle manage Vundle, required
Plugin 'alvan/vim-closetag' " Auto-insert closing tag
Plugin 'cohama/lexima.vim' " Auto matching pairs
Plugin 'ctrlp/ctrlp.vim' " Fuzzy-finder
Plugin 'ervandew/supertab' " Allow overloading of tab
Plugin 'flazz/vim-colorschemes' " Colorscheme pack
Plugin 'glts/vim-textobj-comment' " Define a comment text object using textobj-user
Plugin 'honza/vim-snippets' " Snippet library
Plugin 'kana/vim-textobj-user' " Declarative API for custom text objects
Plugin 'mileszs/ack.vim' " Enable ack/ag for searching
Plugin 'nelstrom/vim-textobj-rubyblock' " Ruby block text objects
Plugin 'ntpeters/vim-better-whitespace' " Whitespace highlighting and trimming
Plugin 'scrooloose/nerdcommenter' " Adds easy comment toggling
Plugin 'scrooloose/syntastic' " Syntax checker
Plugin 'sheerun/vim-polyglot' " Many languages, syntax, etc.
Plugin 'sjl/vitality.vim'     " FocusGained,FocusLost events piped from iTerm2
Plugin 'thoughtbot/vim-rspec' " Lightweight integration with rspec
Plugin 'tpope/tpope-vim-abolish' " Utilities for refactoring/abbreviating/converting variations of words
Plugin 'tpope/vim-bundler' " Integration with Gemfiles
Plugin 'tpope/vim-fugitive' " Add nice git bindings/interactions
Plugin 'tpope/vim-ragtag' " Some goodies for better tag manipulation in XML-ish documents
Plugin 'tpope/vim-rails' " Tons of features for rails projects
Plugin 'tpope/vim-rake' " Nicer file navigation for ruby libraries
Plugin 'tpope/vim-repeat'   " Make . work with vim-surround and other plugins
Plugin 'tpope/vim-surround' " Handle quotes, parens, tags much more easily
Plugin 'tpope/vim-unimpaired' " A variety of pair-wise key bindings
Plugin 'vim-ruby/vim-ruby' " Install vim-ruby to get latest version (not bundled version)
Plugin 'vim-scripts/YankRing.vim' " Emacs-flavored kill-ring

call vundle#end()            " required
filetype plugin indent on    " required

runtime macros/matchit.vim

call s:SourceConfigFilesIn('rcfiles')
